### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by VISTALL** [consulo/long-term-todo#12]
Motivations:
 * plugins can run any processes without user asking, in background
 * plugins can access to internet and push any data without restrictions

plugin.xml
```xml
<consulo-plugin>
   <permissions>
        <permission type="PROCESS" />
        <permission type="INTERNET">
            <permission-option>https://test.com/*</permission-option>    
        </permission>
   </permissions>
</consulo-plugin>
```

Permissions must be show in plugin info page.

**Comment by unv-unv** [comment]
I've checked plugins page in settings. I don't see description of permissions on plugin info page. Am I doing something wrong?

**Comment by VISTALL** [comment]
For now plugins page not show them :)

**Comment by VISTALL** [comment]
Also I'm not fill permissions for plugins - need write them. Just added support

**Comment by unv-unv** [comment]
OK :)

**Comment by VISTALL** [comment]
If enable Permission check in EAP, running any java app(.net or others) will throw error like No permission PROCESS for plugin.

I will add permissions in plugin.xml for each plugins. Need some time

**Comment by VISTALL** [comment]
Example of permission view in near version

![](https://klikr.org/27d74defe44d94a1e62b07bb3322.png)

**Comment by unv-unv** [comment]
I've checked in latest nightly version. Now I can see plugin permissions and some plugins have them specified. Though permissions are displayed with just internal identifier names which aren't well-understandable by user.

Please add user-readable descriptions like:
- PROCESS — plugin can run background processes without asking user
- SOCKET — plugin can access to internet and push any data without restrictions

**Comment by VISTALL** [comment]
Yeah - names are internal. In future need add some localization and warning before installation.
